### ISSUE TITLE
1.10.2 Some vanilla seeds

### ISSUE THREAD

**Issue by darkmtbg2** [AgriCraft/AgriCraft#1016]
agricraft a17 version(A18 crashes with ActAdd)

Sugar canes amd beet seeds are unable to get seeds of and plant into Cropsticks unless you cross breed them and jei doesnt show the sugarcane mutation with Beet and Wheat

**Comment by Hexogenx** [comment]
@darkmtbg2 Did you manage to get Beet seeds somehow? I've been trying to start Agricraft but I cannot get Beets to work, which I need for Sugarcane, which has no recipe as you have mentioned, so I had to read through the config files to find out it's made with Beet.

**Comment by CodesCubesAndCrashes** [comment]
There's [some discussion](https://github.com/AgriCraft/AgriPlants/issues/34#issuecomment-324314685) over on the AgriPlants repository, where the JSONs are kept. It includes the necessary edits to mimic the vanilla behavior. 

As for the beets, I was able to plant the vanilla beetroot seeds on AgriCraft crops just fine in a20, don't know if or what was wrong before. The seeds themselves are harder to get in the first place, since you have to find a village, if that's what you meant.

**Comment by CodesCubesAndCrashes** [comment]
I've added updates to the JSONs to allow cactus, carrots, mushrooms, and sugar canes to be planted directly onto crop sticks, instead of only the AgriCraft seeds. Vanilla beet seeds still seem to be working fine. I can plant vanilla seeds onto the crop sticks, and I can plant the modified ones you get as a result (with the extra NBT data) onto vanilla farmland. So these changes will be in a21.

**Comment by CodesCubesAndCrashes** [comment]
I've made a slight tweak to the fix for this: In these JSONs, I added the `agri_seed` to the front of the seed lists, before the vanilla items. This way both are accepted, but the plant drops the inedible AgriCraft seed instead of the fruit. A worthwhile tradeoff, I think, to avoid losing it among the normal drops. The tweak will be in a future release (a22?), but this original issue is done.
