### ISSUE TITLE
Both Mushrooms cannot grow

### ISSUE THREAD

**Issue by Meth962** [AgriCraft/AgriCraft#1029]
Playing in 1.10.2, I noticed that mushroom spores can spread naturally but they will not grow. I've proven this by replacing the naturally spread one with a hacked in one from JEI and suddenly it's able to grow. Happens on both brown and red spores.

http://imgur.com/a/YaFFG

Soil, light level, and air block requirements are met.

**Comment by Meth962** [comment]
Maybe it's due to the fact that there are duplicate plants for both of these? 
\vanilla\plants\red_mushroom_plant.json
\vanilla\plants\redshroom_plan.json

\vanilla\plants\brown_mushroom_plant.json
\vanilla\plants\brownshroom_plant.json

**Comment by TokkenGmr** [comment]
@RlonRyan I assume that the following should be removed from the AgriPlants Repo? They do the exact same thing, only difference is the format of the name.  

\vanilla\plants\redshroom_plan.json
\vanilla\plants\brownshroom_plant.json

**Comment by Meth962** [comment]
Turns out it's a much bigger issue than I thought. I'm seeing it on cactus as well. Same thing where naturally spreading crops "cannot grow" even though they should. I haven't tested to see if this is also an issue with double cropsticks or not but replacing the natural grown plant with a seed works though. Then again, in general seeing lots of strangeness with the plants. At one time I couldn't place a cactus seed on sand & crop sticks and no error was showing in the log.

**Comment by CodesCubesAndCrashes** [comment]
So, I was hoping to either verify that this issue has been resolved, or to figure out what is going on here. Because there's been reports of offspring not growing on and off for a while, and the screenshots show something is clearly going wrong. Unfortunately, I can't stick the photo into my debugger. Boo. And I've had some good and bad results so far. 

## The Good

I had a bunch of success, where I was able to get mushrooms and other plants to grow after spreading. I tested spreading to both single and double (ie cross) crop sticks, and I tested both in singleplayer and on a dedicated server. In all of these cases, the plants spread and grew. 

I did find one similar bug: plants that spread to single (ie regular) crop sticks don't check the soil below their destination. So a cactus can grow up fully in a crop on sand, then spread into a crop on farmland, and then get stuck there, unable to grow. I'm going to write a fix for that, it's a silly oversight. But that doesn't explain what's going on in @Meth962's screenshots. 

## The Bad

I was checking things out with the magnifying glasses, and I started seeing weird stuff. For example, the magnifying glass reports daytime light levels, instead of the current light levels. And at night, it reports fertility as the opposite of what it does during the day. WAILA reported the correct fertility meanwhile, and normal testing has confirmed that plants and mushrooms correctly grow or don't grow depending on the sun. But the magnifying glass stuff is weird. Because it uses `world.getLightFromNeighbors(pos.up())` just like the growth requirements do. The obvious catch is that the glass runs on the client side, and the growth runs on the server side. But this is the first I've heard of such a huge difference in results. 

## The Questions

* So...
* Were people using a19, a18, or a17? July was after a19 came out, but maybe the OP hadn't updated yet.
* Can anyone recreate the original bug? And if so, can you upload the save?
* When the bug happened, how were people determining that the plants couldn't grow? Was it always thru the magnifying glass, or was it confirmed with other tools, such as WAILA or TOP?
* Some reports said this was a problem with plants that spread to single crops specifically. Does anyone remember problems with double crops too?
* In recent versions of AgriCraft, the mod won't let you plant a seed if it can't currently grow at that location. (Fixed for an upcoming release, btw.) This has meant that seed planting would get silently blocked at night. If that explains some of the weirdness, what things remain unexplained?
* Basically, does this issue still exist? (More of a question for myself.) 

## (And The Screenshots)
![agricraft growth after spreading - 02](https://user-images.githubusercontent.com/28678248/31651346-362ab870-b2d0-11e7-8f4e-1ad04f4bdc22.png)
↳ These plants spread out from the center crop to the four adjacent ones. All of these were regular (single) crops. 
![agricraft growth after spreading - 01](https://user-images.githubusercontent.com/28678248/31651345-3613c958-b2d0-11e7-868c-0c6e21e5ee33.png)
↳ All combinations: both colors, both JSON variations (to be fixed), and both single and double crop sticks. The cross crop tests are the uphill half, and consisted of a single cross crop surrounded by mature mushrooms. 
![agricraft growth after spreading - 03](https://user-images.githubusercontent.com/28678248/31651347-364115de-b2d0-11e7-8a74-67150b54537b.png)
↳ Here we can see the mushrooms that have spread out onto the sand blocks, and so it can't grow now. 
![agricraft growth after spreading - 04](https://user-images.githubusercontent.com/28678248/31651348-36574944-b2d0-11e7-8afc-b89cf59aa68d.png)
↳ **Opposite land, part 1 of 4** - Night time, with the magnifying glass results for all three crops, and the WAILA screen for mushrooms. You can see how the magnifying results are backwards. Meanwhile the mushrooms are fertile because it's dark enough. 
![agricraft growth after spreading - 05](https://user-images.githubusercontent.com/28678248/31651349-366e75ec-b2d0-11e7-9f83-33a2ff9b633d.png)
↳ **Opposite land, part 2 of 4** - Night time, and the WAILA screen for the cactus. It's too dark for the cactus. 
![agricraft growth after spreading - 07](https://user-images.githubusercontent.com/28678248/31651351-36ad03ac-b2d0-11e7-8586-51cd8cf3b5f0.png)
↳ **Opposite land, part 3 of 4** - Day time, with the magnifying result and WAILA for the mushrooms. Both are correct, since it is too bright for the mushrooms. 
![agricraft growth after spreading - 08](https://user-images.githubusercontent.com/28678248/31651352-36c29a64-b2d0-11e7-9977-9bd2dd449821.png)
↳ **Opposite land, part 4 of 4** - Day time, with the magnifying result and WAILA for the cactus. Also both correct, since the sun is out. 
* **Small note:** Take a look at the mushroom plus sand screenshot. Notice that it's dark out and the magnifying glass agrees with WAILA. The inability to grow is because of the soil, whereas the quirks in the last four photos are all lighting based.

**Comment by gwakefield** [comment]
Those are definitely interesting findings. I wonder if they were related to what I was seeing.

I looked back at the install of FTB and see it's running the a17 version in the modpack, or more specifically...
agricraft-2.0.0-0.10.0-a17.jar

That's the problem with this horrid modpacks like FTB, no one updates them or makes sure they're working in the pack. Suppose it would be too much work to test, but should at least be updated.
