### ISSUE TITLE
Crops spread to single crop sticks but not to cross crops (a19)

### ISSUE THREAD

**Issue by Undrhil** [AgriCraft/AgriCraft#1038]
Basically, I setup a 7-1-7 crop plot using Seeds (Wheat).  First square is a single crop stick.  The next 14 squares are cross-crop sticks.  The wheat grows to mature but then never spreads.  I removed the cross-crop stick on the neighboring square and the wheat immediately spread to that square.  Is there a configuration option for the cross-crops to work or should they just work at default?

**Comment by InfinityRaider** [comment]
Sounds like a bug to me

**Comment by CodesCubesAndCrashes** [comment]
Mm, I think I've seen the SpreadStrategy happen, but it's worth re-testing. The reason the wheat successfully spreads onto the regular crop is because there's actually two different ways for a plant to spread. If a growth tick happens to a mature plant, it'll try to spread to all four neighbors. And if a growth tick happens to an empty cross crop, then it'll pick one random mature neighbor, and try to spread them into the empty spot. So the problem lies with the second system.

@Undrhil: Can I trouble you to report back a few things? 
- What is your "Mutation Chance" set to in the config? Heads up, an annoying quirk currently is that any change to this setting will only take effect after restarting the client. The mod reads the value during initialization, and sets up the strategy index, but it doesn't get updated after that, only added on to.
- What is the spread chance for wheat in your JSON? "0.1"?
- Is the Wheat planted in a corner of the 7x7 farm?
- Are you using any growth boosts? 
- ... I might think of more. 

I need to get in front a debugger, to see which parts are acting like expected. Fingers crossed?

**Comment by StrangeBard** [comment]
So I'm using the most recent version and I have noticed this as well with wheat. I can answer a few of those questions you asked the other guy as well. The wheat is planted at 2 corners but the farm is smaller, the spread chance is the default 0.1, the mutation chance is .4, and I'm not using any growth boosts.

**Comment by Chupp4-Jo3** [comment]
Not sure if this is related but I'm getting a similar issue where my plants won't spread to cross crops after hours even with the aid of a watering can but will spread fine to normal crops. I have (multiple) 4 x 4 farms with each having anywhere from 1 to 4 plants and the strongest plant with cross crops next to it. The plant won't spread after multiple attempts at messing with configs and lots (and I mean lots) of waiting, but when i remove the cross crops leaving normal ones replicates in <20 seconds.

https://pastebin.com/LELLf1mk <-- config.cfg

side note: I have messed with the config for soil adding that in case it helps

https://pastebin.com/WPJrcEiX <-- farmland_soil.json
