### ISSUE TITLE
Some changed JSON files on the server are missing from the client.

### ISSUE THREAD

**Issue by Sang-bin** [AgriCraft/AgriCraft#1056]
Server settings are not copied completely
For example, harvestcraft's coffee_plant.json is present on the server but not on the client.

**Comment by CodesCubesAndCrashes** [comment]
Hi! Could you provide the excerpt from the server's logs from when it starts and loads up AgriCraft, and also another from when a player connects? It says things like "Sending plants to player". In the client's logs there's similar messages when they connect. It should say that the plants were recieved [sic], and possibly have warnings about problems with saving the new files. Finally, a copy of the coffee_plant.json would be handy. I don't see any obvious goofs in the code that could send some plants but skip others. So I can't do more than guess. For example, I wonder if maybe the server doesn't successfully load the plant, and so it's not in the registry when all the others get sent. Thank you!

**Comment by redbaron148** [comment]
I have a similar problem.  I'm running pam's harvestcraft and natura and cotton and barley are in both mods.  It seems my single player client only uses the pam's harvestcraft seeds/produce while the server only uses the natura seeds/produce.  

I think this is caused by both mods having the same plant config.  For whatever reason the server decides to use natura's config file rather than harvestcraft's and since harvestcraft's file is a "duplicate" it doesn't think it needs to send it to the client.

**Comment by CodesCubesAndCrashes** [comment]
@redbaron148 Could you check your `config/agricraft/json` folder? There should be a folder called default that will have your single-player plants, and a folder named after your server. Could you compare what files each one has? The plant files get divided up into folders by mod, so plants with the same name shouldn't collide like that.

Also, it would be great if I could get those server and client log files. Even better would be if you could temporarily remove all the JSON files, so that when you connect the transfers will happen and get visibly logged. 

Thank you!
