### ISSUE TITLE
Texture changes in configs not working?

### ISSUE THREAD

**Issue by TechnoColt** [AgriCraft/AgriCraft#1061]
I've been using AgriCraft in FTB Beyond pretty much without issue, however, I noticed that canola plants from ActuallyAdditions had missing textures at later growth stages. Looking through the config, it's clear that it references textures that don't exist (it goes up to stage 6 whereas the AA textures only go up to stage 4). I changed the config in an effort to make it only use the textures that actually exist, but it does not seem to be taking effect, as it is still using the wrong textures for the growth stages. Is there something else I need to do to make this change?

Edit: I forgot to mention that this was on version 2.0.0-0.10.0-a17.

**Comment by CodesCubesAndCrashes** [comment]
The good news is that that issue is fixed already. You can just update AgriCraft and InfinityLib, and then delete the JSONs so that it recreates the new correct defaults. 

If you're curious, [here's the fix](https://github.com/AgriCraft/AgriPlants/commit/15976a2d4094fb02f16a5c5051f4feb9817bcf50).

Alternatively, you can download just the [fixed JSON](https://github.com/AgriCraft/AgriPlants/blob/master/mod_actuallyadditions/canola_plant.json). But a17 is more than one version behind, so I think updating would be better.

Last note: if you would like advice or help with a JSON or such, please upload the file to a pastebin, and provide the link? Unfortunately I can't guess what is wrong with your edits.

Cheers!

**Comment by TechnoColt** [comment]
Thanks much! I think I'll go with the JSONs for now as I'm running a small server and updating the entire mod would require all players to update.

**Comment by CodesCubesAndCrashes** [comment]
Did updating the mod fix the problem? Not sure why that the JSON didn't work. :( Did you replace it on both the server and the client, or just one side?
