### ISSUE TITLE
Add Capabilities based fluid support

### ISSUE THREAD

**Issue by wizard1399** [AgriCraft/AgriCraft#1067]
On the .19 version, the rain tanks will not interact with anything that is not the vanilla bucket.

**Comment by CodesCubesAndCrashes** [comment]
##### [Note: this is an uninformed response. It's just as likely I'm completely wrong.] 
I took a peek at this after you pointed it out. The code in the tanks uses the depreciated `net.minecraftforge.fluids.IFluidHandler` interface, instead of the newer (1.10+) `net.minecraftforge.fluids.capability.IFluidHandler` one. 

I don't know what all else needs to be changed with the tanks for them to function with general pipes, and no idea how much work that update would take. Given that compatibility with other mods is supposed to come after the core mod mechanics are finished, I can't offer a time estimate either. 

###### That said, this could be fun. And the difference between the two interfaces *seems* small. So there's a tiny, tiny possibility that it could be not so hard, if that's all it takes.
