### ISSUE TITLE
[Suggestion] Compatibility with AA Fertilizer

### ISSUE THREAD

**Issue by ethanator2008** [AgriCraft/AgriCraft#1074]
Actually Additions has a fertilizer item that works the same way as bonemeal. If it could be used on crops, that would be nice.

**Comment by darthvader45** [comment]
If it overrides bonemeal code then it should work.

**Comment by CodesCubesAndCrashes** [comment]
Sorta like darthvader45 says, [AA's Fertilizer](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemFertilizer.java#L38) simply invokes the `ItemDye#applyBonemeal` method. That vanilla code is just built around the IGrowable interface.

I've got an update written that adds support for that interface, so this feature should be coming soon. Or at least a basic version of it.

**Comment by CodesCubesAndCrashes** [comment]
The a21 branch adds support for the IGrowable interface to the AgriCraft crop sticks. That means it works with Fertilizer from AA, Forestry, and the ones from Thermal Foundation. :grin: Right now the trick is that you need to crouch when right clicking on the crop sticks. This is because the block handles the activation before the item has a chance.

![agricraft igrowable fertilizers 01](https://user-images.githubusercontent.com/28678248/31852174-1c810a7c-b628-11e7-844d-6a1f03442a5f.png)
![agricraft igrowable fertilizers 02](https://user-images.githubusercontent.com/28678248/31852175-1c97e0da-b628-11e7-9a61-9bbc14ddf475.png)

The IC2 Fertilizer doesn't seem to work, I haven't looked more closely yet. Ditto for the Natura Bone Meal Bag. And the Roots Growth Powder. And yes, I'm adding a wiki page with all of the examples I've found.
