### ISSUE TITLE
Seed Analyzer bug

### ISSUE THREAD

**Issue by StarZxz** [AgriCraft/AgriCraft#1082]
I encountered a problem with version 1.10.2 of the agricraft-2.0.0-0.10.0-a19.jar, when i put the Seed Analyzer into the ground, I could not open its GUI, what happened to me Only installed this mod and infinitylib-0.11.0

**Comment by CodesCubesAndCrashes** [comment]
Hi! 

This is fixed in a20 and a21, which can be found in the releases. You can also downgrade InfinityLib to 0.10, that works too. 

There's already a few threads about this bug, so I'm going to close this as a duplicate. But feel free to follow up with questions if none of those options work for you.

Cheers!

**Comment by StarZxz** [comment]
oh，Thank you very much。now my game very well!THANK YOU : )
