### ISSUE TITLE
Different farmland types

### ISSUE THREAD

**Issue by TimGoll** [AgriCraft/AgriCraft#1176]
I'm using the newest version fpr 1.12.2 and I have a question. I tried to place crop sticks on farmland of other mods (Rustic, Farming for Blockheds) and it wasn't possible. Is there somewhere a config option, where I can define valid farmlands? Because I was unable to find it. Thank you!

**Comment by TimGoll** [comment]
Thank you!

**Comment by TimGoll** [comment]
@TokkenGmr Can you please explain me what I'm doing wrong? I've already ched the wiki (https://github.com/AgriCraft/AgriCraft/wiki/AgriJSON) and tried multiple thing, but it doesn't work.

![image](https://user-images.githubusercontent.com/13639408/44796142-a96cbb00-abac-11e8-90ca-980a6b3c3a83.png) 
(Path)

Json:
```json
{
  "path": "mod_farmingforblockheads/soils/fertilized_farmland_healthy.json",
  "enabled": true,
  "id": "fertilized_farmland_healthy",
  "name": "fertilized_farmland_healthy",
  "varients": [
    {
      "item": "minecraft:dirt",
      "meta": 2,
      "tags": "",
      "ignoreMeta": false,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": false
    }
  ]
}
```

I don't get where the block id is defined. Does agricraft get this id from the filepath?

**Comment by TokkenGmr** [comment]
Ok, let me see if I can help a little bit more. 

First of all are you using minetweaker? The reason I ask is because "farmingforblockheads" may not be the actual name of the mod. It may be an issue with upper and lower case. Notice in the example I gave you ( mod_Botania/soils/podzol_soil.json ) Minetweaker will allow you to see the Mods "actual" name with proper casing as well as give you the correct name for the block you are trying to use. In the JSON you created you used the following
 ( item": "minecraft:dirt",
      "meta": 2, )

That line is incorrect, it is referring back to Podzol. You need to have that line refer to the item you want to use from farmingforblockheads.

So it may not be working for a couple of reasons.

A. Casing on mod name may be incorrect
B.  "id": "fertilized_farmland_healthy", can be named pretty much anything but you need to add "_soil" to 
     the end (healthy_farmland_soil)
    "name": "fertilized_farmland_healthy", would be something like (Healthy Farmland)
C. ( item": "minecraft:dirt",
     "meta": 2, )
Is for sure wrong you will need to get the actual name of the block you want to use and any meta info attached to the block. Meta info is the number after the name, if no number then meta is 0.

B and C both need to be fixed. You can also use F3+H to help get some of the information but minetweaker is the best option. 

Feel free to ask me any questions I know this was winded, I just did not know a better way to state it all

**Comment by TimGoll** [comment]
Wow, that's really nice. Thank you. I'll try my best!

Yes, I'm using crafttweaker and I have some modding experience (started porting carpenters to 1.12.2 with new machines but failed at the rendering code. https://github.com/TimGoll/facading). You should add this description to the wiki!

**Comment by TimGoll** [comment]
Okay, I figured it out. There is a setting `"ignoreMeta": true,` which is really important for soil! I made rustic and farming for blockheads work, but I still have problems with biomes o plenty and PrimalCore. I just wanted to update you.

**Comment by TimGoll** [comment]
I dont't get why PrimalCore and BiomesO'Plenty aren't working. Maybe you can see a error:

Ingame:
![image](https://user-images.githubusercontent.com/13639408/44848159-0ec8b680-ac56-11e8-957c-c3bb19a915aa.png)

Path:
![image](https://user-images.githubusercontent.com/13639408/44848184-1f792c80-ac56-11e8-92ba-93b31d6fa7ac.png)

Code:
```json
{
  "path": "mod_primal/soils/nether_farmland_soil.json",
  "enabled": true,
  "id": "nether_farmland_soil",
  "name": "nether_farmland",
  "varients": [
    {
      "item": "primal\t:nether_farmland",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    }
  ]
}
```

**Comment by TimGoll** [comment]
Wow, never mind. I'm stupid. I had some typos in the files........ Thanks again. I'll add some mutation files and a Pullrequest after that. At least if you're interested

**Comment by TokkenGmr** [comment]
I am not sure to be honest, I have never tried more than one farmland for a plant. It looks like you could add in an extra variant in the farmland_soil JSON. Something like [this](https://pastebin.com/TwR1PY3J).
however you may have to just add each soil type to each plant under the soil section. Wish I had more information.

**Comment by TimGoll** [comment]
Tried it. It does work the way I hoped it would. Thank you again. I might add a Pullrequest to the wiki if this is possible.

**Comment by TimGoll** [comment]
Since you are an expert:
1) is there a way to make agri craft less bone meal intensive? I need app. 25 bonemeal to grow a crop. about 3 if it is planted on normal soil. I tried some settings in the config file, but they haven't changed much
2) are you able to disable weed? I haven't found an option to do so
3) maybe this one is a bug: Agri craft does not accept compost as a fertilizer. Yes the option is enabled.
