### ISSUE TITLE
[1.12.2] Crop Sticks covering up plant growth info.

### ISSUE THREAD

**Issue by Birdpup** [AgriCraft/AgriCraft#1216]
## Quick description
Agricraft crop sticks seem to be covering up what crops are displayed underneath. The crops are still visible, but no information can be garnered from them by hovering over (in the case of growth percentages provided by HWYLA and other mods). Additionally, the crop sticks seem to lack an 'outline' to their texture. By extension, magnifying glasses cannot be used, as they can only see the crop sticks, and not the crop.

## Related issues and searches
Searching of similar issues has not garnered any additional results.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: Agricraft-2 12.0-1.12.0-a6
* InfinityLib: 0.14.0

I have also used other mods such as Mystical Agriculture and Pam's Harvestcraft, but the issues have arisen with vanilla seeds as well. I have tried on all iterations of base vanilla with just Agricraft, as well as with these additional mods.

## Steps to replicate the issue

1. Installed Agricraft for Version 1.12.2, latest forge version.
2. Tilled farmland in a creative or survival world.
3. Placed down singular crop sticks and then planted seeds on them, be it vanilla or otherwise.

## Expectations and explanations
In older versions of Agricraft, you were able to see the growth rate of the crops when mousing over them. Cases of this occuring correctly seem to be in 1.7.0 packs (Regrowth comes to mind) but has also worked in cases of Agrarian Skies 2 and the like.

## Your environment

* How are you playing?
  * Operating System: Windows 7
  * Launcher: Twitch/Standard Minecraft Launched
  * Modpack: Custom
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
There are no crash logs.

## Screenshots (or videos)
https://i.imgur.com/HwW5JcI.png

**Comment by OmegaX123** [comment]
Can confirm this issue is not isolated to just you, I'm experiencing the same issue in "Project Ozone 3". This is a separate issue from the "HWYLA/WAILA and Agricraft aren't compatible" issue that WASAILA was created to fix, because said modpack has WASAILA installed as well and the crops' stats are still hidden/blocked/whatever by the crop sticks.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.

**Comment by FrAmed46** [comment]
just ignoring all the bugs for old versions? great dev

**Comment by InfinityRaider** [comment]
The contributors to this project have worked on it out of passion only, choosing to sacrifice precious spare time to do so.
Since we all have our own lives outside of modding Minecraft, our time is limited and we have to set our priorities. We have no obligations to you or anyone.

The project is fully open source, all legacy issues are tagged accordingly and are therefore perfectly traceable.
If you want them solved, you may try learning to mod Minecraft yourself, or commission a dev to do it for you.

If you cannot engage in constructive dialogue, I would insist you take your negativity elsewhere.
