### ISSUE TITLE
AgriCraft item in inventory produces client crash with "java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES"

### ISSUE THREAD

**Issue by katubug** [AgriCraft/AgriCraft#1242]
# Quick description
Here's a fun one. I haven't seen a crash like this before, so I'm afraid I can't provide you with a lot of context. I received this from one of my players, and he hasn't yet told me what exactly he was doing when the crash occurred. Seems it was an issue rendering an ingredient - in this case, an AgriCraft grate made of Quark's Vertical Planks (unsure what type of wood).

## Related issues and searches
I searched for both "grate" and had a look through "crash" to see if anything matched. I admit I only scanned the first page, but I didn't see anything that seemed to match.

## Mods and versions used
Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2846-universal
Modpack version (links to current modlist): [1.7.0](http://enthusiasticraft.cf/modpack-update-1-7-0/#modlist)
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6
* InfinityLib: infinitylib-1.12.0
* Quark: Quark-r1.6-177

## Steps to replicate the issue
I'm afraid I can't say, as I haven't been able to replicate. Since it says it was having difficulty rendering in inventory, I'd assume attempting to craft a grate made from Quark's vertical planks?

## Expectations and explanations
Sort of explained in the previous paragraph.

## Your environment
* How are you playing?
  * Operating System: unsure of client. server is ubuntu.
  * Launcher: unsure of client, probably Twitch. Server is pterodactyl.
  * Modpack: EnthusiastiCraft (my modpack, link is above)
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save
^ I am not sure how to answer this. The world is brand new but playerdata was carried over. I cannot replicate in singleplayer because I'm not entirely sure what I'm trying to replicate.

## Links to crash logs, stack traces, etc

https://paste.dimdev.org/abetonoquc.mccrash

I apologize for the lack of information. As I learn more or if I'm able to replicate, I will update this ticket.

**Comment by jolandepoel** [comment]
Right, I'm not sure of the author of Agricraft is still updating this mod. (And if they aren't, perhaps they could consider removing the alpha warning message?)

I've had a similar problem. Agricraft and 'constructing vertices' I thought it was Effortless Building (since that's what I'm using when it crashes: placing blocks in lines and walls and such) I was using Twilight Forest blocks and building in creative, but after the first crash, it crashed simply when opening my inventory (and thus accessing JEI) I've asked the JEI developer on a related crash, and he confirmed that it was Agricraft causing the crash. 

I've rolled back my world, disabled some things of the mod "Charm" in the config (the changes to furnaces, I think) and it's running smoothly again. 

In the pastebin my crashes (all 3 in one paste, simply search 'PASTE' to go to the next one)

Agricraft constructing vertices error: https://pastebin.com/VEicQEiw

I hope these related crashes are helpful in pinning down the problem.
