### ISSUE TITLE
Game crashes when interacting with the seed analyzer

### ISSUE THREAD

**Issue by Mazereck** [AgriCraft/AgriCraft#1463]
## Quick description
When using pehkui mod and accessing the agricraft seed analyzer it causes the game to crash

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 3.1.2
* InfinityLib: 2.1.2
* Pehkui: 3.3.2
* origins forge: 1.4.1.1
* bucolic orgins forge: 3.2
(happens with just these mods installed but if you need the full mod list its in the crash report)

## Steps to replicate the issue
1. have the above mods installed
2. place the seed analyzer down
3. interact and crash

## Your environment
* Operating System: Windows 10
* What kind of server: Multiplayer
* Game Modes: Survival

## Links to crash logs, stack traces, etc
https://paste.ee/p/qBwZL

**Comment by InfinityRaider** [comment]
Report to pehkui

**Comment by Virtuoel** [comment]
After some testing, turns out this is caused by [InfinityLib](https://github.com/InfinityRaider/InfinityLib)'s dynamic camera, specifically the way it's [instantiated](https://github.com/InfinityRaider/InfinityLib/blob/3451458b0c6416d99a45abdea8a1c73914195553/src/main/java/com/infinityraider/infinitylib/modules/dynamiccamera/DynamicCamera.java#L35), using `Unsafe` and having to [initialize fields that shouldn't be null](https://github.com/InfinityRaider/InfinityLib/blob/3451458b0c6416d99a45abdea8a1c73914195553/src/main/java/com/infinityraider/infinitylib/utility/UnsafeUtil.java#L211-L212), which unsurprisingly can't take into account [fields added by a mod's mixins](https://github.com/Virtuoel/Pehkui/blob/fedb16ed00d46ffe1153e383eb63c811c82b9975/src/main/java/virtuoel/pehkui/mixin/EntityMixin.java#L42) whose types are not in that list.

**Comment by InfinityRaider** [comment]
Yip, but I can't do anything on my end to fix this, whereas a simple null check on pehkui would fix this.
