### ISSUE TITLE
NoSuchFieldError: MECHANICAL_HARVESTER

### ISSUE THREAD

**Issue by DemonSeedxp** [AgriCraft/AgriCraft#1510]
So for a bit of context and how I wound up here, I was attempting to add AgriCraft to an instance of FTB Plexiglass Mountain ver 1.2.4  I've been playing on. But after I first added the mod and reloaded I received the errors seen below.
 
`Mod agricraft only supports create 0.5.1.b or above Currently, create is 0.5.0.d` 
`Mod agricraft requires forge 40.2 or above Currently, forge is 40.1.84` 
`Mod agricraft requires infinitylib 1.18.2-2.1.4 or above Currently, infinitylib is not installed` 
(since dependency wasn't listed on modpage of Modrinth)
 
So I started going through the modpacks files and learned it wasn't going to be too easy to upgrade it's create mod and as best I can tell practically impossible to upgrade the forge version it's running, which left me one option, downgrade AgriCraft until compatible version was found (because I couldn't find any documentation of what forge version each jar was built referencing)  which took me back to AgriCraft 3.1.4 to get the forge error gone.

But once I did, a new error started getting thrown which was 
Failure message: AgriCraft (agricraft) encountered an error during the common_setup event phase
		`java.lang.NoSuchFieldError: MECHANICAL_HARVESTER`
This happened starting in 3.1.4  and kept happening all the way to 3.1.0

So I'm guessing it must be the version of Create that's installed that is the issue, but I don't really know for sure. Which is why I decided to come here and see what I could learn.

I thought maybe something could have been cached during one of the previous failed startups that might have caused the same error in every version I tried, but again, just a guess. 

Any idea what the problem I'm having here is?
I'm attaching my [crash-reports folder](https://drive.google.com/file/d/1qpf9aQ-CziHAoeVVf1eTe2vSuHWINSkN/view?usp=sharing) zipped up since every report contained within are all AgriCraft generated

**Comment by Ketheroth** [comment]
agricraft crashes with create because they don't have an api so we have to hook into their code, and when they change their code, it breaks
agricraft 3.1.4 crashes with recent versions of create because the field moved
agricraft 3.1.5 fixed the crash with create < 0.5.1.b while moving to forge 40.2 as there was no reason to stay on 40.1, and create need 40.2 anyway
agricraft 3.1.6 fixed the crash with create 0.5.1.b (because the field moved again)

So if you want to play with agricraft and create, you have 3 possibilities : 
\- update you game with forge 40.2 + agricraft 3.1.6 + create 0.5.1.b
\- stay on older version with forge 40.1.x + agricraft 3.1.4 and search for the create version not making agricraft break
\- use whatever version of forge, agricraft and create while disabling create compatibility in the config (create contraptions won't be able to interact with agricraft crops though)

sorry for the inconvenience

**Comment by DemonSeedxp** [comment]
Wow, sounds like a total pain to support them since they can't be bothered to build a proper API for other mods to plug into. Surprised you are even trying to hit their constantly moving target.  

I wasn't aware you had a config option to disable create support so I'll find that and turn it off, since create doesn't support any of the other mods in this pack either, so no since in worrying about it. 

Honestly I'm mostly after agricrafts irrigation system more than anything else so I won't even be impacted by the lack of create support . 

Thanks for taking the time to help me out. Very much appreciated.

**Comment by DemonSeedxp** [comment]
Not to add more work on you but maybe having some sort of exception handling on your backend to ignore create mod if the installed version isn't what your code is expecting would help prevent this from happening again to someone else in the future. Just a thought...

Thanks again
