### ISSUE TITLE
Return of the compat

### ISSUE THREAD

**Issue by InfinityRaider** [AgriCraft/AgriCraft#572]
- [x] JEI
- [ ] Computercraft & OpenComputers
- [ ] AppleCore
- [ ] Tinker's Construct
- [ ] Hydraulicraft
- [ ] IC2 classic (#661)
- [x] HarvestCraft
- [ ] MFR
- [ ] Botania (Horn of the Wild)

**Comment by Deriboy** [comment]
What needs to be done in order to get computer comparability working with the CCSA? According to https://github.com/MightyPirates/OpenComputers/issues/2322, it seems like Agricraft's side of things isn't providing sufficient information for Open Computers to write compatibility for it. 

I am interested in getting the computer aspect of this issue solved if someone could point me in the right direction.

**Comment by InfinityRaider** [comment]
Ah, how ambitious we were...

**Comment by brendanvos** [comment]
Does this mean you've given up on the computer controlled seed analyzer? Does it work with anything at the moment?

I stumbled across this issue while trying to figure out how to get it to work with OpenComputers, but looks like it's not currently compatible? 
There's no documentation for the computer controlled seed analyzer on agridocs, so I can't figure out if it's compatible with anything.

**Comment by InfinityRaider** [comment]
Depends on what version you are on.

And no, this means that I have given up on any version that is earlier than 1.16.
