### ISSUE TITLE
Cannot get seeds from give command

### ISSUE THREAD

**Issue by Volune** [AgriCraft/AgriCraft#712]
I'm trying to use the following command to get potato seeds, but I always get aurigold seeds.
```
/give Player agricraft:agri_seed 1 0 {agri_seed:"potato_plant"}
```

Is something wrong in the command?

**Comment by DragGon7601** [comment]
For an older version (I don't see why it would have changed, but you never know) I use:

/give @p AgriCraft:seedPotato 4 0 {strength: 1, analyzed: 0, growth: 1, gain: 1}

You can change the str/growth/gain to what ever you want. :P

**Comment by InfinityRaider** [comment]
@DragGon7601 this is for 1.7.10, in the 1.10 (unreleased) versions, all seeds use the same ID and the plant type is defined via the nbt.

**Comment by RlonRyan** [comment]
I wrote the seed system, and I have no idea how to use the give command... So...

**Comment by Kryptic01** [comment]
So nobody knows how to spawn in custom seeds without JEI?

**Comment by RlonRyan** [comment]
I think it would require a longer chat message now, given the number of fields seeds have (there is a fair bit of information to store).

**Comment by Kryptic01** [comment]
I was wondering if there is a method to Show the JEI commands because JEI can give you custom seeds

**Comment by quixQuery** [comment]
Use ALL the NBT tags.
Note: this cannot be done in chat, it must be done via command block because the code is too long.

NBT tags:
agri_seed
agri_strength
agri_growth
agri_gain
agri_analyzed

example:
`/give Player agricraft:agri_seed 1 0 {agri_seed:"sugarcane_plant", agri_analyzed:0b, agri_strength:1b, agri_gain:1b,  agri_growth:1b }`

How did I figure this out?
F3 + H and looking at the NBT data tags on an already spawned in seed. I tried adding tags in one at a time, getting the "generic seed" every time until I tried all the tags.

Why are the "b"s there?
Ask the mod dev. I honestly have no clue.

Now if you find a way to get this to work with crafttweaker and modtweaker scripts let me know please :).

**Comment by TehNut** [comment]
The b stands for `byte`. It's there so MC knows to deserialize it as a `byte` instead of an `int`.

**Comment by tyler489** [comment]
In 1.10 didnt they change how many characters you could use in a msg or was that 1.11

**Comment by coolgaza16** [comment]
what is the command for nether wart with stats gr10 ga10 st10 as i cant get them to cross crop at all i can get them to cross breed to make other plants but not with themselves so can only have  gr1 ga1 st1 on it
