### ISSUE TITLE
Cannot craft blocks/items. (Recipes not in sync between server and client?)

### ISSUE THREAD

**Issue by quantumtweaker** [AgriCraft/AgriCraft#783]
Currently experiencing these to following issues:

https://gfycat.com/YellowishConfusedBlacklemur (goes for all blocks and items for AgriCraft)
https://gfycat.com/PlushHandsomeIberianbarbel (goes for all placed blocks for AgriCraft)

Forge version: 12.18.3.2185

Exception from the server console for both instances: http://pastebin.com/EM6CnfNk

**Comment by RlonRyan** [comment]
The gifs are a nice touch. They make the issue very clear.

**Comment by RlonRyan** [comment]
This might be an issue with the dang @SideOnly annotations.

**Comment by quantumtweaker** [comment]
Not very good at describing issues sometimes and the developers I work with at work love when I send gifs of issues.

**Comment by RlonRyan** [comment]
I think I have this fixed. Not sure if the item crafting thing is still an issue though...

**Comment by RlonRyan** [comment]
Will need confirmation of fix in a6.

**Comment by quantumtweaker** [comment]
@RlonRyan still broken. Same issue as before. Unable to craft blocks/items nor break ones found in villages.

**Comment by RlonRyan** [comment]
@quantumtweaker Thanks for the update!

**Comment by RlonRyan** [comment]
Do you have any newer logs for this?

**Comment by quantumtweaker** [comment]
Not currently as I disabled Agricraft, though I could probably get some @RlonRyan

**Comment by RlonRyan** [comment]
Oh, sorry to hear that... But modding can be tricky at times, so...

**Comment by quantumtweaker** [comment]
I just re-enabled it on my custom direwolf pack with the latest release. ill let you know how it goes

**Comment by quantumtweaker** [comment]
Still cant craft Agricraft blocks :/

**Comment by quantumtweaker** [comment]
woops xD

**Comment by RlonRyan** [comment]
Hmm... I guess I'll have to look into why blocks aren't crafting...

**Comment by RlonRyan** [comment]
I can't get the crafting issue to occur locally... I'll probably have to setup a fresh environment...

**Comment by quantumtweaker** [comment]
I can give you the curse profile export for the custom direwolf20 pack if you'd like.

**Comment by RlonRyan** [comment]
That might work...

**Comment by quantumtweaker** [comment]
[RPG Tech Pack-1.0.5.zip](https://github.com/InfinityRaider/AgriCraft/files/728169/RPG.Tech.Pack-1.0.5.zip)

**Comment by icedown** [comment]
I just encountered this same issue on FTB Beyond 1.0.1.  I was initially able to craft them the first day or so of the server, now it happens like posted above.  It uses 2.0.0-0.6.0-a10.  Can send logs if needed.  There are no errors generated when it is happening but there may be something on startup.

**Comment by Vaygrim** [comment]
Creating and testing a pack that uses this mod, and we've run across the same issue type. It was specifically isolated to Oak Channels (channels of other wood types worked fine), and even these crafted FINE in single player worlds.. while remaining broken in multiplayer servers.

Our solution was to just throw in a recipe for the item via Minetweaker and this resolved things fine. Issue appears to be the fact that a bunch of the crafting recipes are registered client-side, not server-side.

**Comment by RlonRyan** [comment]
How unusual... I hope I can figure out what the root issue is soon...

**Comment by InjuredWolf** [comment]
Just an extra note, I found that the agricraft nuggets for iron, diamond, emerald, etc. cannot be crafted into their respective ingot/gem. Same issue as the gif in OP. Also server-based. Did not test in single player, but judging by the fact that the recipe was in JEI, it most likely worked in SP.

**Comment by Vaygrim** [comment]
In recent versions of AgriCraft in our [pack](https://minecraft.curseforge.com/projects/coop-life) we have the same issue now. Very recent problem where turning a Tin ingot into nuggets forces them to be Tin Nuggets which have NO use and cannot be turned back into Tin Ingots. We had to force-add crafting recipes (via Craft Tweaker) to make these nuggets usable in any fashion.

**Comment by InfinityRaider** [comment]
Better to make a separate issue for this since itll be probably overlooked as a comment in this issue.

**Comment by darthvader45** [comment]
Is anyone still encountering this issue in the latest alpha?

**Comment by CodesCubesAndCrashes** [comment]
@RlonRyan It occurred to me that I wasn't sure how the configs stay in sync between the client and server, and how items or blocks get disabled. I guessed that since the config menu is created by Forge just by adding annotations, that the client-server sync of options was handled by Forge too. Since then, I've learned that a mod has to do its own syncing of settings. 

So I wonder if a hiccup in that process could lead to these crafting problems? Where the server has the item disabled, and so the recipe doesn't exist there, while the client and GUI do show it. This would fit with the single- versus multi-player contrast, and why it wouldn't happen in quick and simple local testing. I've read through a bunch of the AgriConfig related files, but I don't have a grasp on all the parts of this yet. 

#### Misc observations: 
* I have noticed that enabling and disabling Irrigation, for example, requires a restart to take affect. 
* Water Tank blocks didn't get disabled though. 
* Also, that Trowels, Rakes, and such aren't showing up in the Tools config menu currently. 
* I semi-unsuccessfully tested some of this out by launching two clients locally. For the first one I disabled Irrigation, started the client up, created a new world, confirmed that most of the Irrigation stuff was gone from JEI. Then I opened the world to LAN. I then started a second client, and connected to the first one, confirmed the channels were in JEI, and then tried to craft one. The second client crashed once I clicked, but because of a NPE in the rendering. So, testing it this way doesn't work currently.
* Other weird thing: on the second client JEI continuously threw errors about the tooltip for the items that were disabled on the first client. 
* Oh, and the first client would freeze when quitting to the title after some of these situations. Haven't identified the pattern though, but it seems to be if the second client has connected or not. Probably unrelated to this issue.

**Comment by darthvader45** [comment]
When this issue is fully fixed, can this issue be closed?
