### ISSUE TITLE
Crops not respecting base item metadata

### ISSUE THREAD

**Issue by Tsukiumy** [AgriCraft/AgriCraft#887]
i was setting the resorce seeds, ans started with the botania one, and just to test for the TE ones, i added the need for petal blocks for it to be planted, but put it to be especifically for the petal tipe, because the use the same item id with just diferent meta, like the TE ones, and it just looked if it has the correct ID and ignored the meta
here the JSON
https://gist.github.com/Tsukiumy/ce39683b6750d1ea8747ac4c1aa4ad39
it makes the need of the block, but not respect the meta
(on a side note i found that the mod dont like that much if you remove the required block underneath and make the tickrate skyrocket to force a growth with ome sorte of tick acceleration tool like torcherino or acceleration wand)

**Comment by TokkenGmr** [comment]
I just tested the petal block as a base and it respected the meta data for each petal block no problem.

In regards to the increase of tick rate and breaking of "base" item. I had this problem as well, however mine was a fully grown plant. I broke the "base" block, then tried to harvest and the game crashes until I remove the required "base" block from the json. It also had a torcherino next to it

**Comment by Tsukiumy** [comment]
it respects in the regard of the need, but you can put any color, and it just let plant and grow, the problem is that i wanna make it a little bit harder to get platinum, as i can just put a cooper block under it and it will grow :(

**Comment by TokkenGmr** [comment]
I think it might be the torcherino allowing for it to grow no matter what is called for as the "base" block. If I place a torcherino next to any custom plant no matter what block I use as a "base" it will grow.

**Comment by Tsukiumy** [comment]
i tested with just a watering can too, and it grows, im just waiting the new version where the growth rate is fixed to make a 10/10/10 seed to make the test, but its not respecting the metadata, cuz you can plant even if you dont have the right block under, its only looking for the id, JEI shows the block correctly, not cicling tru all the metas, but the seed just looking for the ID and not the meta. I see that you made some tests putting the right seeds over the right block, but to test you just need to use a block with the correct ID but the wrong meta and you will see what im talking about.

**Comment by TokkenGmr** [comment]
I have tested more than just the correct seeds on the correct blocks, I tried every combo I could think of.

There is an issue yes, however it is not just the meta data of the block. In your example you used the black petal block as the base block. I realize that jei/nei shows it correctly, If you were to use say wood planks, black petal block, or even white petal block. It doesnt matter what block is there the plant will grow. I would ask if the plant grows by itself without any tick acceleration, but due to the bug in growth chance it takes stupid long for plants to grow at the moment. I have let 2 plants sit for the last 4 hours one has black petal block which is correct and other has white petal block incorrect. The only one that has grown is the one on the black. Both started at 12.5% one on black is only at 39.5% and other is at 12.5% still. If I apply acceleration they both grow.

**Comment by Tsukiumy** [comment]
i made a test, made then 10/10/10 to make the bonus chance growth better, and let it sit for a few ours while i tested the bugs on MPS, and it grow basically at the same speed, so no, it isnt working, i just put the side by side, chunkloaded the area and waited to see.o well, now is just wait RlonRyan senpai to ~~notice me~~ find the problem and solve it :D. ~~so we can find more and more bugs~~

**Comment by RlonRyan** [comment]
Fixed.
