### ISSUE TITLE
Cant disable login info

### ISSUE THREAD

**Issue by tfox83** [AgriCraft/AgriCraft#889]
I need a way to disable the login donation/alpha info in FTB modpacks, not seeing it in the config set.  Thanks.

![image](https://cloud.githubusercontent.com/assets/4246308/24365478/e2487ada-12ca-11e7-9b54-7752cf4a7633.png)

**Comment by RlonRyan** [comment]
The notification will be removed in the release versions of AgriCraft.

The notification was added as to ensure users knew they were using an alpha version and stability is not guaranteed.

**Comment by phit** [comment]
Can you change the color to white, yellow or something more commonly used, FTB ended up just removing this message by hiding all messsages that are in that dark aqua color. Breaking servers and refusing to fix it.

**Comment by RlonRyan** [comment]
Time to randomize the colors then I suppose...

**Comment by tfox83** [comment]
If you just added the alpha notice on one line I wouldn't block it, but I cannot have donation links in official FTB packs.

**Comment by TehNut** [comment]
Honestly this is on FTB for including a mod in *very* early alpha. The first few versions of Beyond even had the build that destroyed framerates.

**Comment by i9hdkill** [comment]
I totally understand why you put the Alpha reminder. But instead of that direct donation link, maybe add a line like that:
"Find out how to help develop AgriCraft here: -Link to your Github or Github wiki page-
This would solve tfox83 concern, that I fully understand, but also solves server owners issue, that ftb beyond just broke ALL servers with that silly client mod blocking all messages with "&3" in it.

**Comment by dualspiral** [comment]
> but I cannot have donation links in official FTB packs.

Then don't include the mod, simple as that. If they want to include such a message, that's their perogative, and you shouldn't be fooling around with it (especially removing it in such a lazy and disastorous way), especially when you are making money from putting these mod packs together and potentially depriving mod authors from potential donations. They put in the work to make these mods - they deserve to have donation notices if they so choose.

**Comment by TehNut** [comment]
The donation link isn't even for Agricraft. It's for Agriculture in general.

**Comment by Mohron** [comment]
> If they want to include such a message, that's their perogative

Either way he's right. It's the dev's right to include a message supporting a cause they believe in.

**Comment by Jaskirat-Boparai** [comment]
> (especially removing it in such a lazy and disastorous way)

But Dual, FTB don't support Sponge! 
https://i.gyazo.com/thumb/1200/_6b6e64b30ca61dabf88732dd3516b234-png.jpg

And I mean, why would they? Considering Sponge is the only available plugin API for 1.10 for server owners to use with forge modpacks! *Breathes Heavily*

/rantover

**Comment by nan0bug00** [comment]
This isn't just a Sponge issue.  You can include color coding that would be passed to in game chat in a shell script you use to handle restarts and other common admin tasks.  You could have these color codes in messages passed by a panel.  This is a lazy hack to remove something that shouldn't be removed in the first place.  I understand where FTB is coming from with having notification spam, as a modpack developer you always want the ability to disable that, but if you don't have that ability in a config file, the solution isn't to break things for other people by using some ugly hack to disable all chat in a certain color.

It's not about providing Sponge support.  It's about breaking expected behavior for whatever mod, script, or plugin API wants to use specific chat formatting.

**Comment by Rongmario** [comment]
>If you don't like the mod's functionality, whatever it may be
>Don't add it


FTB really has gone downhill past year.

**Comment by RlonRyan** [comment]
I'm willing to add a config option that removes the links from the alpha warnings on the condition that you promise not to remove alternate one-line alpha warnings.

The new config option will not be enabled by default however, and it will be up to you to set it in your packs.

If you had specified in the original issue that your problem was with the links in the warnings, the majority of this drama likely could have been avoided, given that I understand there exist possible legal issues regarding donation links (be they charitable or not).

2.0.0a15 should be out by Monday.

**Comment by tfox83** [comment]
Thank you for looking into this again.  As of the last Beyond public beta we redid our regex to properly hide repeated incoming chat messages during login.  This fix will solve the issue that sponge server owners were having with color codes.  

Since Agricraft is not the only alpha mod in this pack we have decided its only fair to notify the players in a less abrasive way that some mods are still in an alpha state and contain bugs, and how/where to submit issues, either via on the main menu of the pack or a notification before the menu screen.  We are actively working on this solution now and will have it in the next update.  

Things have been put in place to prevent mods in an alpha state to release in a future FTB pack, including reaching out to the developers directly when using an alpha mod during development.  I think we can all agree that since the start of MC 1.8 stability is a bit less in any major modpack and we know over time this will change, just as it did with MC 1.7.  We actively update Beyond weekly and fix as many bugs as we possibly can, and make sure that mod bugs are reported in the correct places.

**Comment by RypoFalem** [comment]
"sponge server owners were having with color codes."

This is a vanilla issue by the way. I reported the issue first and do not use sponge. Chat colors are vanilla functionality, for future reference, and I even provided an example vanilla command to show you that in the report.

**Comment by KocLobster** [comment]
Does Curse/FTB make money off of their modpacks?

That just seems so greedy to ask for the mod author to remove the donation link if they do.

**Comment by InfinityRaider** [comment]
Yes they do, through ad revenue. And Curse is so kind as to share some of that revenue with the modders.

Agricraft is not and will never be developped with the intention to generate revenue. As a result there will never be donation links. The donation links which RlonRyan added to the alpha warnings are just to add a hint of humor to them.
However this is enough off topic for this issue, if you wish to discuss revenue streams in minecraft modding, I prefer you do that on reddit or the FTB forums, thank you.

**Comment by RlonRyan** [comment]
An alpha with the modification mentioned earlier has been released, and as such this issue is drawn to a close.

Exit, Stage Right.

**Comment by KaneHart** [comment]
Lmao. This is priceless.
