### ISSUE TITLE
Harvesting compatibility

### ISSUE THREAD

**Issue by Vaygrim** [AgriCraft/AgriCraft#912]
Agricraft was designed with compatibility in mind for mods such as MFR or Thaumcraft, for setting up autofarms. At present in 1.10.2 there is no MFR and no Thaumcraft. I cannot locate a farming automation mod that actually SUPPORTS AgriCraft's cropsticks method.

What are the odds we could either get some compatibility settings for this (a mode to plant and mutate crops without cropsticks) OR .. an actual autofarming machine put into the mod?

**Comment by InfinityRaider** [comment]
The mod is still in alpha, it has been rewritten almost completely since the 1.8 port.
The basic philosophy was: first get the mod to work by itself, then add in the compatibility back in.
Given that the former isn't the case yet, the latter won't be there tomorrow.
However compatibility IS on the agenda.

**Comment by InfinityRaider** [comment]
See issue #572
