### ISSUE TITLE
Weed Overtake Logic Reversed

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#945]
See https://www.reddit.com/r/feedthebeast/comments/6a881q/ftb_beyond_unofficial_changelog_for_the_v160/dhhzq78/?context=5 for original report.

**Comment by CodesCubesAndCrashes** [comment]
Fixed by PR #946 

**Summary:** The Modify Weed Spawning Mechanics [commit](https://github.com/AgriCraft/AgriCraft/commit/314a6eaa284a0ee5988825811b92bef513b44798#diff-e92d41d0d84f12f89141e0d86116150bR256) introduced a typo replacing the less-than with a greater-than inequality. As a result, an Aggressive plant with Strength *lower* than a neighboring plant would always spread and replace the other plant.

**Comment by InfinityRaider** [comment]
Nice detective work! I tip my hat to you sir.

**Comment by CodesCubesAndCrashes** [comment]
Thank you! :)
