### ISSUE TITLE
Cannot access Seed Analyzer

### ISSUE THREAD

**Issue by Xanjaxn** [AgriCraft/AgriCraft#947]
Just like the title says, I crafted the seed analyzer but I can't access the interface.

**Comment by RlonRyan** [comment]
What version?
Multiplayer or Singleplayer?
What environment?

**Comment by Xanjaxn** [comment]
This is single player, 1.10.2 on a windows 10 home edition laptop.

**Comment by RlonRyan** [comment]
AgriCraft version?

**Comment by Xanjaxn** [comment]
I went to check and realized I wasn't up to date, I am now and the seed analyzer is working. Sorry, and thanks for the help!

**Comment by RlonRyan** [comment]
Glad it's working now!

**Comment by Semajor** [comment]
I'm currently experiencing this particular issue on a19 of Agricraft. One moment the seed analyzer was working, and now it just isn't. I've broken it and crafted a new one several times, but I cannot get the interface to appear. It also doesn't seem to be gamemode related since it's broken even in creative mode. 

Prior to it breaking I only analyzed 3 seeds - wheat, wither skeleton from Mystical Agriculture, and nether star from Mystical Aggradditions. If you need a world download to help figure this out, let me know and I'll throw you my current build. Modlist is included below in case there's a known conflict that I missed in my search of the issues.

[Foolcraft Custom Modlist.txt](https://github.com/AgriCraft/AgriCraft/files/1160489/Foolcraft.Custom.Modlist.txt)
