### ISSUE TITLE
Mystical Agriculture crops randomly appearing on open crop sticks

### ISSUE THREAD

**Issue by thelordofdino4** [AgriCraft/AgriCraft#969]
When placing down new crop sticks I will receive a seemingly random crop from mystical agriculture, instead of a weed for example. Same goes for mutation plots. Not entirely sure what causes this glitch. Any help would be appreciated.

**Comment by InjuredWolf** [comment]
This is a bug with the way they are auto-generated. I found I had to go through and edit the configs for the plants. Need to edit the 'spawn_chance' to 0.0 (for some reason some of them are 0.1 or something, I'm guessing whoever made the defaults accidentally made the spawn chance the 0.1 like the spread chance)

**Comment by TokkenGmr** [comment]
Are you both using the current version of agricraft? Which plants are still spreading? Everything looks correct on the agriplants repo. This was also brought up in #955.
Just loaded  fresh instance and the JSON files seem to be correct

**Comment by RlonRyan** [comment]
Yeah, this was partially my fault in not going through all the json files provided to the AgriPlants repo with a fine-toothed comb before merging them. Also, the corrected JSON files somehow seemed to have slipped out of the a17 release, but will be in the a18 release when it comes out.

A word of warning, the a18 release might be a while because I decided to completely refactor the API (yet again...)...

@InjuredWolf's solution is the correct one for the time being.
