### ISSUE TITLE
Disable Vanilla Farming does not block Mystical agriculture planting.

### ISSUE THREAD

**Issue by Dilnu** [AgriCraft/AgriCraft#980]
Hi, I'm running 1.10.2 Forge 12.8.3.2297 with Agricraft 2.0.0-0.10.0-a17 and Mystical Agriculture 1.5.4

On this version with the disable vanilla farming set to true and I've tested with potatos that it's working I can still plant mystical agriculture seeds. Is there something I'm missing?

**Comment by RlonRyan** [comment]
Mystical Agriculture plants must plant in a different manner than do vanilla plants. I'll have to look into making the farming blocker more generalized.

**Comment by Dilnu** [comment]
Thanks, I really appreciate it.

**Comment by RlonRyan** [comment]
Never mind, this is actually an issue with the fact that AgriCraft seeds are disparate from Mystical Agriculture seeds.

You see, AgriCraft will not block any item that cannot be used as a seed on crops. This is a precaution to ensure that the disable farming option will not wind up disabling a plant that cannot otherwise be planted or grown.

I think this can be fixed by either using the Mystical Agriculture seeds as the AgriCraft seeds or by adding a field to the JSON files specifying items that a plant would block when disable farming is on.

**Comment by Dilnu** [comment]
Oh, when I noticed this I was testing with one of the seeds that was broken, that makes perfect sense. I just retested with a seed working with agricraft and indeed things work as intended thanks and sorry for the false report.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
