### ISSUE TITLE
Shift right clicking cropsticks to place the cross sticks crashes server

### ISSUE THREAD

**Issue by scalda** [AgriCraft/AgriCraft#989]
Hi, 

I have just updated agricraft and infiniraider

latest version
agricraft-2.0.0-0.10.0-a18.jar
infinitylib-0.10.0.jar

Whenever I place cross sticks via shift right clicking on tilled soil it crashes the server
[crahs report](https://pastebin.com/qz4eHZaK)

regards

Scalda
(FoolCraft Modpack Dev)

**Comment by RlonRyan** [comment]
Yay! Fatal error in fancy new code... And I thought I had gotten better at this...

**Comment by RlonRyan** [comment]
Wait... Wat... How can you get an abstract method error at runtime? Something seriously hinky is going on here... I'm not even sure if that can be debugged...

Uh @tehnut HALP!

**Comment by CodesCubesAndCrashes** [comment]
**Correction:** I'm going to think aloud about something that just occurred to me? In IAgriCrop, getWorld() is declared with default access, not public. That means the method signature is different from TileEntity.getWorld(), which *is* public. I feel like that should still be a compile time issue, but seems worth looking in to. 

#### Original post follows... 

I'm tidying up my research tabs, and since it felt like the discussions on these pages might be relevant, I wanted to share them. 
* [Oracle](http://bugs.java.com/view_bug.do?bug_id=6519118), bug report about calling inherited methods from abstract classes in separate packages. Hard to say if this is similar enough. 
* [Artima](http://www.artima.com/objectsandjava/webuscript/PolymorphismInterfaces1.html), see Static versus Dynamic Binding. I thought this was going to be helpful, since the `liq.gurgle()` example is about unexpected method resolution. But really the bug in agricraft isn't one of the three exceptional cases they list. 
* [StackOverflow](https://stackoverflow.com/questions/32839503/why-does-a-superclass-implement-interface-methods-which-are-supposed-to-be-imple), confirms that a child can fulfill an interface using methods inherited from an abstract parent. So that's indeed supposed to work fine. 
* [Apprize](http://apprize.info/javascript/action/10.html), focuses on default methods in interfaces, but does discuss well the resolution rules.

**Comment by RlonRyan** [comment]
I guess I could rename the method and provide an implementation in the class. The dispatch doesn't make any sense though... And why is this issue just showing up now?

**Comment by Redhandjane** [comment]
I'm not sure if it's related, but I have the same versions and I crash when I try to use Extra Utilities on cross crop sticks as well as when I right click a set of cross crops.

**Comment by CodesCubesAndCrashes** [comment]
This is a very weird bug, yup. It hasn't happened to me yet, but I also haven't tried using Actually Additions plus LordDan1989's instructions in #997 to recreate it.

As for the timing, well the May 24th commit (e7c4f0e) changed SpreadStrategy ([L27](https://github.com/AgriCraft/AgriCraft/commit/e7c4f0e78d174638b9a33d0ab45e280ed9b738c0#diff-c250519a93f34620dad1d96a2b986205R27)) and MutateStrategy to call `crop.getWorld()`, and also added `getWorld()` to the IAgriCrop interface ([L37](https://github.com/AgriCraft/AgriCraft/commit/e7c4f0e78d174638b9a33d0ab45e280ed9b738c0#diff-dfab8295dd12650e9602cacd8064c385R37)). The a17 release was before that, and a18 after that. 

A lot of the help for AbstractMethodErrors blames bytecode that was cached instead of recompiled properly to reflect some new source code, but since TileEntityCrop *didn't* have a getWorld method removed, that doesn't make sense. Hm.

Also: how about just adding the method to `TileEntityCrop.java`? (Instead of renaming it.)
```java 
@Override
public World getWorld() {
    return super.getWorld();
}
```

**Comment by CodesCubesAndCrashes** [comment]
Yup, I think I've found the answer. 
> CovertJaguar commented on Jun 11, 2016 
> Also the infamous "getWorld()" bugs. ;)
> https://github.com/md-5/SpecialSource/issues/12#issuecomment-225336526

**Comment by RlonRyan** [comment]
Well this bug is fixed thanks to @CodesCubesAndCrashes... I'm still leaving the wat label applied to it though, because, seriously, wat Forge? [Wat](https://www.destroyallsoftware.com/talks/wat)?
